Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job             count    min threads    max threads
------------  -------  -------------  -------------
all                 1              1              1
enriched_tfs        1              1              1
get_kmers           1              1              1
gkm_predict         1              1              1
total               4              1              1

Select jobs to execute...

[Sun May 15 22:38:14 2022]
rule get_kmers:
    output: data/9mers.fa
    jobid: 3
    wildcards: word_length=9
    resources: tmpdir=/tmp

[Sun May 15 22:38:15 2022]
Finished job 3.
1 of 4 steps (25%) done
Select jobs to execute...

[Sun May 15 22:38:15 2022]
rule gkm_predict:
    input: data/9mers.fa, model/wgEncodeSydhTfbsGm12878Nfe2hStdAlnRep0.model.txt
    output: weights/wgEncodeSydhTfbsGm12878Nfe2hStdAlnRep0.svmw.txt
    jobid: 2
    wildcards: sample=wgEncodeSydhTfbsGm12878Nfe2hStdAlnRep0
    resources: tmpdir=/tmp

[Sun May 15 22:38:16 2022]
Finished job 2.
2 of 4 steps (50%) done
Select jobs to execute...

[Sun May 15 22:38:16 2022]
rule enriched_tfs:
    input: weights/wgEncodeSydhTfbsGm12878Nfe2hStdAlnRep0.svmw.txt
    output: expr_enriched_tfs.wgEncodeSydhTfbsGm12878Nfe2hStdAlnRep0.txt
    jobid: 1
    wildcards: sample=wgEncodeSydhTfbsGm12878Nfe2hStdAlnRep0
    resources: tmpdir=/tmp

[Sun May 15 22:38:16 2022]
Error in rule enriched_tfs:
    jobid: 1
    output: expr_enriched_tfs.wgEncodeSydhTfbsGm12878Nfe2hStdAlnRep0.txt

RuleException:
CalledProcessError in line 41 of /gpfs/scratch/jtl334/thesis/pipeline/workflow/Snakefile:
Command 'set -euo pipefail;  /gpfs/home/jtl334/.conda/envs/pipeline/bin/python3.7 /gpfs/scratch/jtl334/thesis/pipeline/.snakemake/scripts/tmpsjjmsazu.count_kmers_per_motif.py' returned non-zero exit status 1.
  File "/gpfs/scratch/jtl334/thesis/pipeline/workflow/Snakefile", line 41, in __rule_enriched_tfs
  File "/gpfs/home/jtl334/.conda/envs/pipeline/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-05-15T223814.187325.snakemake.log
